In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.55783399, 0.97141017, 0.26051626, 0.20918555, 0.9374981 ])

In [17]:
np.random.rand(5,5)

array([[0.81232549, 0.08489828, 0.13660895, 0.33730486, 0.780822  ],
       [0.44343378, 0.15640441, 0.87699036, 0.82436384, 0.75496363],
       [0.59610145, 0.85079731, 0.92785087, 0.7304951 , 0.15077725],
       [0.06520864, 0.54764918, 0.13999795, 0.66671063, 0.26682467],
       [0.0234071 , 0.65188314, 0.0544562 , 0.31158714, 0.47514007]])

In [18]:
np.random.randn(2)

array([-1.34592282,  1.13318819])

In [19]:
np.random.randint(1,100)

64

In [22]:
np.random.randint(1,100,10)

array([19,  4, 41, 19,  1, 85, 62, 35, 88, 90])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
ranarr

array([26, 49,  6, 49, 24,  3, 12,  7,  7, 13])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr

array([26, 49,  6, 49, 24,  3, 12,  7,  7, 13])

In [29]:
ranarr.max()

49

In [30]:
ranarr.min()

3

In [31]:
ranarr.argmax()

1

In [32]:
ranarr.argmin()


5

In [34]:
arr.shape

(25,)

In [35]:
arr.dtype

dtype('int64')

In [36]:
from numpy.random import randint

In [37]:
randint(2, 10)

2